export const GET_VIDEOGAMES = "GET_VIDEOGAMES";
export const SEARCH_VIDEOGAMES = "SEARCH_VIDEOGAMES";
export const DETAIL_VIDEOGAMES = "DETAIL_VIDEOGAMES";
export const FILTER_GENRE = "FILTER_GENRE";
export const ALL_GENRE = "ALL_GENRE";
export const SORT_VIDEOGAMES_ASC_DESC = "SORT_VIDEOGAMES_ASC_DESC";
export const SORT_VIDEOGAMES_RATING = "SORT_VIDEOGAMES_RATING";